# Generated by Django 5.0.4 on 2024-10-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(choices=[('', 'Selecione um assunto'), ('descontos', 'Descontos'), ('consultoria', 'Consultoria'), ('elogios', 'Elogios'), ('reclamações', 'Reclamações'), ('outros', 'Outros')], default='', max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mensagem', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'db_table': 'contato',
            },
        ),
    ]
