# Generated by Django 5.0.4 on 2024-11-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='assunto',
            field=models.CharField(choices=[('', 'Selecione um assunto'), ('descontos', 'Descontos'), ('elogios', 'Elogios'), ('reclamações', 'Reclamações'), ('outros', 'Outros')], default='', max_length=100),
        ),
    ]
