# Generated by Django 5.0.4 on 2024-10-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='available_time',
            field=models.TimeField(),
        ),
    ]
