# Generated by Django 5.0.4 on 2024-10-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_consulta_available_time'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consulta',
            table='consulta_patient',
        ),
    ]
