# Generated by Django 5.0.4 on 2024-10-05 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('scheduled', models.BooleanField(default=False)),
                ('available_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.availabledate')),
            ],
        ),
    ]
